# This is a basic workflow to help you get started with Actions

name: debug an action runner

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai

    - name: cmd
      run: |
        echo 1
        exit 0
        echo 2
        echo "strDate=$(TZ=UTC-8 date +%Y-%m-%d)" >> $GITHUB_ENV

          
    - name: Start SSH via tmate
      uses: klever1988/ssh2actions@main
      with:
        mode: ssh
      # Send connection info to Telegram (optional)
      # You can find related documents here: https://core.telegram.org/bots
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        SSH_PASSWORD: ${{secrets.SSH_PASSWORD}}
        SSH_PUBKEY: ${{secrets.SSH_PUBKEY}}
        NGROK_TOKEN: ${{secrets.NGROK_TOKEN}}
        TUNNEL_HOST: ${{secrets.TUNNEL_HOST}}



