name: ssh
on: 
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    
    - name: Update system
      run: |
       sudo sysctl vm.swappiness=0
       nohup sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk &
       sudo -E apt update
       nohup sudo -E apt -y --no-install-recommends install pv jq build-essential cmake asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python2.7 python3 python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler scons antlr3 gperf intltool mkisofs rsync swig &

    
    - name: SSH connection to Actions
      uses: gewplay/debugger-action@master
      
